/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slither;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SlitherTest {

}
