/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slither;

import javax.swing.*;
import java.awt.Point;

import java.awt.GridLayout;
import java.awt.Container;
import java.awt.Color;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Slither extends JFrame {

    private static final Logger logger = LoggerFactory.getLogger(Slither.class);

    final int WINDOW_WIDTH = 900;
    final int WINDOW_HEIGHT = 900;

    public Slither() {
        logger.debug("Creating Frame with size({}, {})", WINDOW_WIDTH, WINDOW_HEIGHT);

        setTitle("Slither");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        setResizable(false);

        setLayout(new GridLayout(3, 1, 30, 30));

        addMenuItemsToPane(this.getContentPane());

        setVisible(true);
    }

    private void addMenuItemsToPane(Container pane) {
        JButton easyButton = new JButton("Start Easy");
        JButton mediumButton = new JButton("Start Medium");
        JButton hardButton = new JButton("Start Hard");

        easyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                logger.debug("easyButton clicked");
                easyButton.setVisible(false);
                mediumButton.setVisible(false);
                hardButton.setVisible(false);

                startGame(pane, 12, 12);
            }
        });
        mediumButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                logger.debug("mediumButton clicked");
                easyButton.setVisible(false);
                mediumButton.setVisible(false);
                hardButton.setVisible(false);

                startGame(pane, 50, 50);
            }
        });
        hardButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                logger.debug("hardButton clicked");
                easyButton.setVisible(false);
                mediumButton.setVisible(false);
                hardButton.setVisible(false);

                startGame(pane, 100, 100);
            }
        });

        pane.add(easyButton);
        pane.add(mediumButton);
        pane.add(hardButton);
    }

    private void startGame(Container pane, int width, int height) {
        logger.debug("Called startGame");
        var g = pane.getGraphics();
        var center = new Point(pane.getWidth() / 2, pane.getHeight() / 2);

        g.setColor(Color.GREEN);
        g.fillRect(center.x, center.y, 10, 10);
    }

    public static void main(String[] args) {
        Slither game = new Slither();
    }
}
